services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rEaLtImEpAnEl
      POSTGRES_DB: realtimepanel
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./realtimepanel-api
    restart: always
    env_file: ./realtimepanel-api/.env.docker
    depends_on:
      - db
    ports:
      - "3001:3001"

  app:
    build: ./realtimepanel-app
    restart: always
    ports:
      - "4201:80"
    depends_on:
      - api

volumes:
  db_data: