version: "3.9"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  realtimepanel-api:
    build: ./realtimepanel-api
    restart: always
    env_file: ./realtimepanel-api/.env
    depends_on:
      - db
    ports:
      - "3000:3000"

  realtimepanel-app:
    build: ./realtimepanel-app
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - realtimepanel-api

volumes:
  db_data: